# src/Comparon\MegacronBundle\Entity\MegaCronHistory.orm.yml
Comparon\MegacronBundle\Entity\MegaCronHistory:
    type: entity
    table: comparon_megacron_history
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        cronJobName:
            column: cronjob_name
            type: string
            length: 255
        started:
            column: started
            type: datetime
        stopped:
            column: stopped
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [ onPrePersist ]